name: Trend check/alert

on:
  schedule:
    - cron: '0 20,21 * * 1-5'
  workflow_dispatch:
    inputs:
      sendTestEmail:
        description: 'Send a test email (true/false)'
        required: true
        default: 'false'
        
jobs:
  check-run:
    runs-on: ubuntu-latest
    outputs:
      run: ${{ steps.check_local_time.outputs.run }}
    steps:
      - name: Check local time
        id: check_local_time
        env: 
          TRIGGER: ${{ github.event_name }}
        run: |
          echo "Trigger: ${TRIGGER}"
          if [[ ${TRIGGER} == 'schedule' ]]; then
            echo "Checking daylight saving time for Eastern Time zone"
            if [[ $CURRENT_HOUR -eq 15 && $CURRENT_MIN -ge 50 ]] || [[ $CURRENT_HOUR -eq 16 && $CURRENT_MIN -le 30 ]]; then
              echo 'Within the targeted time window in the Eastern Time zone!'
              echo "run=True" >> "$GITHUB_OUTPUT"
            else
              echo "Outside the targeted time window. Waiting for next execution..."
              echo "run=False" >> "$GITHUB_OUTPUT"
            fi
          else
            echo 'Trigger is not a scheduled event, omitting time check!'
            echo "run=True" >> "$GITHUB_OUTPUT"
          fi
          
  trend_alert:
    runs-on: ubuntu-latest
    if: needs.check-run.outputs.run == 'True'
    needs: check-run
    
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Cache Python packages
      uses: actions/cache@v4
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install dependencies
      run: |
        pip install yfinance pandas

    - name: Run script
      env:
        SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
        SENDER_PASSWORD: ${{ secrets.SENDER_PASSWORD }}
        RECEIVER_EMAIL: ${{ secrets.RECEIVER_EMAIL }}
      run: python alert.py
              
    - name: Check for changes
      id: git-check
      run: |
        git diff --exit-code || echo "changes=true" >> $GITHUB_ENV

    - name: Commit changes
      if: env.changes == 'true'
      run: |
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'actions@github.com'
        git add .
        git commit -m "Update state"

    - name: Push changes
      if: env.changes == 'true'
      run: git push
      
  send_test_email:
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.sendTestEmail == 'true' }}
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        pip install yfinance pandas
    - name: Send Test Email
      env:
        SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
        SENDER_PASSWORD: ${{ secrets.SENDER_PASSWORD }}
        RECEIVER_EMAIL: ${{ secrets.RECEIVER_EMAIL }}
        SEND_TEST_EMAIL: 'true'
      run: python alert.py
